[
    {
        "Name Of Univ": "NIT",
        "Students": "1000",
        "Location": "Warangal",
        "ID": 1,
        "State": "TS",
        "Branches": "4",
        "Faculty": "25"
    },
    {
        "Name Of Univ": "IIT",
        "Students": "1400",
        "Location": "Hyderabad",
        "ID": 2,
        "State": "Telangana",
        "Branches": "6",
        "Faculty": "30"
    },
    {
        "Name Of Univ": "IIIT",
        "Students": "2000",
        "Location": "Idupudapaya",
        "ID": 3,
        "State": "AP",
        "Branches": "8",
        "Faculty": "35"
    },
    {
        "Name Of Univ": "Padmavathi",
        "Students": "3000",
        "Location": "Tirupathi",
        "ID": 4,
        "State": "AP",
        "Branches": "4",
        "Faculty": "40"
    }
]